# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

 

# Example 1:

# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.

# Example 2:

# Input: s = "", t = "y"
# Output: "y"

 

# Constraints:

#     0 <= s.length <= 1000
#     t.length == s.length + 1
#     s and t consist of lowercase English letters.

# Accepted
# 478.7K
# Submissions
# 797.4K
# Acceptance Rate
# 60.0%

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return t - s
list_val_s =  "abcd", ""
list_val_t = "abcde", "y"
for index,num in enumerate(list_val_s):
    Solution.findTheDifference('Succsess' num,  list_val_t[index])